#!/bin/bash
set -e

DIR=/home/dev/app

# Checkout the repository
[ ! -d "${DIR}/.git" ] && echo "Cloning git repository..." && git clone git@github.com:HayonCS/ea-app.git .

cd $DIR

# Install project Git Hooks
#yarn git:setup-hooks

# Yarn install
[ ! -d "node_modules" ] && echo "Installing node modules..." && yarn install

# Instructions for copying over .gitconfig
# Container name may be different for you.
# Path to the gitconfig file may also be different depending on your system, i.e. linux vs windows.
[ ! -f "/home/dev/config/gitconfig" ] && printf "To copy your host machine's .gitconfig run this from the host:\n\n  docker cp ~/.gitconfig tpe_dev_1:/home/dev/config/gitconfig\n"
