version: "3.7"
services:
  dev:
    build: docker/dev
    command: /usr/local/lib/tail-and-wait
    ipc: host
    volumes:
      - devappdata:/home/dev/app
      - devconfigdata:/home/dev/config
      - subversiondata:/home/svn
      - sambadata:/var/opt/samba
      - ./samba-data:/var/opt/samba-external
    ports:
      - "3000:3000" # Webpack dev server
      - "3001:3001" # Express server
      - "9001:9001" # Storybook
      - "9229:9229" # Debug express server
      - "9230:9230" # Debug bull worker
    environment:
      - MSSQL_CLI_SERVER=sql-server
      - MSSQL_CLI_USER=SA
      - MSSQL_CLI_PASSWORD=YourStrongPassw0rd
      - MSSQL_CLI_TELEMETRY_OPTOUT=True
      - SA_PASSWORD=YourStrongPassw0rd

  redis:
    image: redis:4
    ipc: host
    ports:
      - "6379:6379"

  rest-endpoints:
    build: docker/rest-endpoints
    ports:
      - "3070:3070"

volumes:
  devappdata:
  devconfigdata:
  sqlserverdata:
  subversiondata:
  sambadata:
