export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const UPDATE_USER_DATA = "UPDATE_USER_DATA";
export const UPDATE_USER_GENTEX = "UPDATE_USER_GENTEX";
export const UPDATE_TEAM_GENTEX = "UPDATE_TEAM_GENTEX";
