import * as db from "db";

const seedUsers = [
  {
    Name: "rvandermate",
    Phone: "0000",
    EMail: "del2",
    Manager: "del2",
    Location: "del2",
    ReadOnly: "True",
  },
  {
    Name: "joshua.lareau",
    Phone: "x-4446",
    EMail: "joshua.lareau@gentex.com",
    Manager: "David Slater",
    Location: "Centennial East",
    ReadOnly: "False",
  },
  {
    Name: "jason.lewis",
    Phone: "1234",
    EMail: "jason.lewis@gentex.com",
    Manager: "Dave Slater",
    Location: "Centennial East",
    ReadOnly: "False",
  },
  {
    Name: "nate.hansen",
    Phone: "5678",
    EMail: "nate.hansen@gentex.com",
    Manager: "Dave Slater",
    Location: "Centennial East",
    ReadOnly: "False",
  },
  {
    Name: "chrisc",
    Phone: "0002",
    EMail: "del1",
    Manager: "del1",
    Location: "del1",
    ReadOnly: "True",
  },
  {
    Name: "randy.vandermate",
    Phone: "5164",
    EMail: "randy.vandermate@gentex.com",
    Manager: "Emanuel Chiaburu",
    Location: "Centennial East",
    ReadOnly: "False",
  },
  {
    Name: "chris.cuddohy",
    Phone: "4286",
    EMail: "chris.cuddohy@gentex.com",
    Manager: "Dave Slater",
    Location: "Centennial East",
    ReadOnly: "False",
  },
  {
    Name: "bob.sayers",
    Phone: "5418",
    EMail: "bob.sayers@gentex.com",
    Manager: "Jared Huges",
    Location: "Centennial East",
    ReadOnly: "False",
  },
  {
    Name: "jasen.mcmann",
    Phone: "4979",
    EMail: "Jasen.McMann@Gentex.com",
    Manager: "sdf",
    Location: "Centennial East",
    ReadOnly: "False",
  },
  {
    Name: "scott.hanson",
    Phone: "0001",
    EMail: "scott.hanson@gente.com",
    Manager: "E. Chiaburu",
    Location: "Centennial East",
    ReadOnly: "False",
  },
  {
    Name: "brad.reed",
    Phone: "4457",
    EMail: "Brad.Reed@gentex.com",
    Manager: "David Q Slaters",
    Location: "Centennial East",
    ReadOnly: "False",
  },
  {
    Name: "chris.carter",
    Phone: "616-772-1800 x5055",
    EMail: "chris.carter@gentex.com",
    Manager: "Looby, Jim",
    Location: "Centennial East",
    ReadOnly: "False",
  },
  {
    Name: "david.slater",
    Phone: "98765",
    EMail: "david.slater@gentex.com",
    Manager: "Paul Flynn",
    Location: "Centennial East",
    ReadOnly: "False",
  },
  {
    Name: "dave.slater",
    Phone: "23231",
    EMail: "dave.slater@gente.com",
    Manager: "Paul Flynn",
    Location: "CE",
    ReadOnly: "False",
  },
  {
    Name: "dslater",
    Phone: "2342154",
    EMail: "dave.slater@gentex.com",
    Manager: "Paul Flynn",
    Location: "CE",
    ReadOnly: "False",
  },
  {
    Name: "jon.knorr",
    Phone: "4456",
    EMail: "Jon.Knorr@gentex.com",
    Manager: "Jim Looby",
    Location: "Centennial East",
    ReadOnly: "False",
  },
  {
    Name: "joel.shuman",
    Phone: "616.403.5355",
    EMail: "joel.shuman@gentex.com",
    Manager: "Jared Hughes",
    Location: "Centennial East",
    ReadOnly: "False",
  },
  {
    Name: "harley.steel",
    Phone: "4176",
    EMail: "harley.steel@gentex.com",
    Manager: "Jared Hughes",
    Location: "Centennial East",
    ReadOnly: "False",
  },
  {
    Name: "jacob.dubs",
    Phone: "5862",
    EMail: "jacob.dubs@gentex.com",
    Manager: "Dave Slater",
    Location: "Centennial East",
    ReadOnly: "False",
  },
  {
    Name: "COMBO",
    Phone: "1",
    EMail: "1",
    Manager: "1",
    Location: "Centennial East",
    ReadOnly: "True",
  },
  {
    Name: "jeff.macdonald",
    Phone: "5506",
    EMail: "jeff.macdonald@gentex.com",
    Manager: "Stan Church",
    Location: "James Street",
    ReadOnly: "True",
  },
  {
    Name: "matthew.lueder",
    Phone: "2482173899",
    EMail: "matthew.lueder@gentex.com",
    Manager: "Joshua Lareau",
    Location: "Centennial East",
    ReadOnly: "True",
  },
  {
    Name: "jason.vernon",
    Phone: "4758",
    EMail: "jason.vernon@gentex.com",
    Manager: "slater",
    Location: "Centennial East",
    ReadOnly: "True",
  },
  {
    Name: "jared.hughes",
    Phone: "x5963",
    EMail: "jared.hughes",
    Manager: "Jim Looby",
    Location: "Centennial East",
    ReadOnly: "False",
  },
  {
    Name: "joel.dennison",
    Phone: "x5153",
    EMail: "joel.dennison@gentex.com",
    Manager: "Jared Hughes",
    Location: "Centennial East",
    ReadOnly: "False",
  },
  {
    Name: "daniel.millisor",
    Phone: "x5681",
    EMail: "daniel.millisor@gentex.com",
    Manager: "Jared Hughes",
    Location: "Centennial East",
    ReadOnly: "False",
  },
  {
    Name: "nathan.shoudy",
    Phone: "5419",
    EMail: "nathan.shoudy@gentex.com",
    Manager: "Kevin Miller",
    Location: "Centennial East",
    ReadOnly: "False",
  },
  {
    Name: "PRODSP",
    Phone: "616-402-2828",
    EMail: "jon.knorr",
    Manager: "jim looby",
    Location: "Centennial East",
    ReadOnly: "True",
  },
  {
    Name: "kevin.merdzinski",
    Phone: "5039",
    EMail: "kevin.merdzinski@gentex.com",
    Manager: "Miller",
    Location: "Centennial East",
    ReadOnly: "False",
  },
  {
    Name: "richard.buckley",
    Phone: "4736",
    EMail: "richard.buckley@gentex.com",
    Manager: "Miller",
    Location: "Centennial East",
    ReadOnly: "False",
  },
  {
    Name: "stephen.pierce",
    Phone: "4679",
    EMail: "stephen.pierce@gentex.com",
    Manager: "david.slater",
    Location: "Centennial East",
    ReadOnly: "False",
  },
  {
    Name: "chris.kozak",
    Phone: "5269",
    EMail: "chris.kozak@gentex.com",
    Manager: "Stan Church",
    Location: "James Street",
    ReadOnly: "True",
  },
  {
    Name: "taylor.warczinsky",
    Phone: "989-763-0662",
    EMail: "taylor.warczinsky@gentex.com",
    Manager: "Jim Dratz",
    Location: "Centennial East",
    ReadOnly: "True",
  },
  {
    Name: "Cabdul.Ciise",
    Phone: "5628",
    EMail: "cabdul.ciise@gentex.com",
    Manager: "Jared Hughes",
    Location: "Centennial East",
    ReadOnly: "False",
  },
  {
    Name: "brian.eden",
    Phone: "6167721800",
    EMail: "brian.eden@gentex.com",
    Manager: "Erik Stroude",
    Location: "Centennial East",
    ReadOnly: "True",
  },
  {
    Name: "jeff.harsevoort",
    Phone: "4015",
    EMail: "jeff.harsevoort@gentex.com",
    Manager: "Dustin Darrow",
    Location: "Centennial East",
    ReadOnly: "True",
  },
  {
    Name: "austin.cross",
    Phone: "4695",
    EMail: "austin.cross@gentex.com",
    Manager: "Jared Hughes",
    Location: "Centennial East",
    ReadOnly: "False",
  },
  {
    Name: "Joshua.Grow",
    Phone: "616-594-8122",
    EMail: "joshua.grow@gentex.com",
    Manager: "Bret Cobb",
    Location: "Centennial East",
    ReadOnly: "True",
  },
  {
    Name: "Carl.Lin",
    Phone: "6168867752",
    EMail: "carl.lin@gentex.com",
    Manager: "Jason Dewyse",
    Location: "Centennial East",
    ReadOnly: "True",
  },
  {
    Name: "Matt.Gould",
    Phone: "231-383-1531",
    EMail: "Matt.Gould",
    Manager: "Kevin.Miller",
    Location: "Centennial East",
    ReadOnly: "False",
  },
  {
    Name: "Paul.Prock",
    Phone: "4093572435780943",
    EMail: "paul.prock@gentex.com",
    Manager: "jason dewyse",
    Location: "Centennial East",
    ReadOnly: "True",
  },
  {
    Name: "bill.rininger",
    Phone: "4544",
    EMail: "bill.rininger@gentex.com",
    Manager: "Dave Slater",
    Location: "Centennial East",
    ReadOnly: "False",
  },
  {
    Name: "stephen.mcandrew",
    Phone: "(269) 369-4696",
    EMail: "stephen.mcandrew@gentex.com",
    Manager: "Jared Hughes",
    Location: "Centennial East",
    ReadOnly: "False",
  },
  {
    Name: "dan.hartung",
    Phone: "616-610-0300",
    EMail: "dan.hartung@gentex.com",
    Manager: "Stan Church",
    Location: "Centennial East",
    ReadOnly: "False",
  },
  {
    Name: "Patrick.Beak",
    Phone: "616-402-3023",
    EMail: "patrick.beak@gentex.com",
    Manager: "Kevin Miller",
    Location: "Centennial East",
    ReadOnly: "False",
  },
  {
    Name: "chris.simon",
    Phone: "5388",
    EMail: "chris.simon@gentex.com",
    Manager: "Kevin Miller",
    Location: "Centennial East",
    ReadOnly: "False",
  },
  {
    Name: "joshua.andersen",
    Phone: "8506249773",
    EMail: "joshua.andersen@gentex.com",
    Manager: "Kevin Miller",
    Location: "Centennial East",
    ReadOnly: "False",
  },
  {
    Name: "klintworth.erkes",
    Phone: "6540",
    EMail: "klintworth.erkes@gentex.com",
    Manager: "kevin miller",
    Location: "Centennial East",
    ReadOnly: "False",
  },
  {
    Name: "Rick.Sanchez",
    Phone: "943-glurb",
    EMail: "picklerick@aol.com",
    Manager: "Council of Ricks",
    Location: "Centennial West",
    ReadOnly: "True",
  },
  {
    Name: "kevin.miller",
    Phone: "5137",
    EMail: "kevin.miller@gentex.com",
    Manager: "David Slater",
    Location: "Centennial East",
    ReadOnly: "False",
  },
  {
    Name: "samantha.teskey",
    Phone: "9283664110",
    EMail: "samantha.teskey@gentex.com",
    Manager: "Joshua Lareau",
    Location: "Centennial East",
    ReadOnly: "True",
  },
  {
    Name: "ben.halanski",
    Phone: "4169",
    EMail: "ben.halanski",
    Manager: "Jasen McMann",
    Location: "Centennial East",
    ReadOnly: "False",
  },
  {
    Name: "cherise.gray",
    Phone: "6168799622",
    EMail: "cherise.gray@gentex.com",
    Manager: "Adam Edwards",
    Location: "Centennial East",
    ReadOnly: "True",
  },
  {
    Name: "test.name",
    Phone: "000000",
    EMail: "fake@fake.net",
    Manager: "none",
    Location: "Centennial East",
    ReadOnly: "True",
  },
  {
    Name: "derek.pitcher",
    Phone: "6168365596",
    EMail: "derek.pitcher@gentex.com",
    Manager: "Adam Edwards",
    Location: "Centennial East",
    ReadOnly: "True",
  },
  {
    Name: "don.tapley",
    Phone: "4291",
    EMail: "don.tapley@gentex.com",
    Manager: "Dave Slater",
    Location: "Centennial East",
    ReadOnly: "False",
  },
  {
    Name: "ben.hagberg",
    Phone: "616-312-8718",
    EMail: "ben.hagberg@gentex.com",
    Manager: "Kyle Williams",
    Location: "James Street",
    ReadOnly: "True",
  },
  {
    Name: "robert.spencer",
    Phone: "231-736-9630",
    EMail: "robert.spencer@gentex.com",
    Manager: "Sean Galloway",
    Location: "Centennial East",
    ReadOnly: "True",
  },
  {
    Name: "devin.hunter",
    Phone: "313-498-5436",
    EMail: "devin.hunter@gentex.com",
    Manager: "Sandy Bettis",
    Location: "Centennial East",
    ReadOnly: "True",
  },
  {
    Name: "nick.beezhold",
    Phone: "61677218006643",
    EMail: "nick.beezhold@gentex.com",
    Manager: "Jared Hughes",
    Location: "Centennial East",
    ReadOnly: "False",
  },
  {
    Name: "wanda.weber",
    Phone: "8888",
    EMail: "jjj",
    Manager: "jjj",
    Location: "Centennial East",
    ReadOnly: "True",
  },
  {
    Name: "clivert.eskelsen",
    Phone: "6168342450",
    EMail: "clivert.eskelsen.gentex.com",
    Manager: "Erik",
    Location: "Centennial East",
    ReadOnly: "True",
  },
  {
    Name: "justin.grachan",
    Phone: "+1 616-772-1590 x6577",
    EMail: "justin.grachan@gentex.com",
    Manager: "Church, Stan",
    Location: "James Street",
    ReadOnly: "False",
  },
  {
    Name: "james.truszkowski",
    Phone: "586-596-4694",
    EMail: "james.truszkowski@gentex.com",
    Manager: "David Slater",
    Location: "Centennial East",
    ReadOnly: "False",
  },
  {
    Name: "cent_ea1",
    Phone: "fake",
    EMail: "fake",
    Manager: "fake",
    Location: "Centennial East",
    ReadOnly: "True",
  },
  {
    Name: "sbtester",
    Phone: "5865964694",
    EMail: "james.truszkowski",
    Manager: "David Slater",
    Location: "Centennial East",
    ReadOnly: "True",
  },
  {
    Name: "mike.zomerlei",
    Phone: "4852",
    EMail: "mike.zomerlei@gentex.com",
    Manager: "Kevin Miller",
    Location: "Centennial East",
    ReadOnly: "False",
  },
  {
    Name: "Prototype",
    Phone: "4276",
    EMail: "scott.thompson",
    Manager: "Dan Quitanilla",
    Location: "Centennial East",
    ReadOnly: "False",
  },
  {
    Name: "nick.sklenicka",
    Phone: "616-610-1411",
    EMail: "Nick.Sklenicka",
    Manager: "Jasen.McMann",
    Location: "North Riley",
    ReadOnly: "True",
  },
  {
    Name: "nathan.reeder",
    Phone: "6167724863",
    EMail: "nathan.reeder@gentex.com",
    Manager: "Ryan Cowherd",
    Location: "Centennial East",
    ReadOnly: "True",
  },
  {
    Name: "michael.foster",
    Phone: "3135251696",
    EMail: "michael.foster@gentex.com",
    Manager: "Jerry",
    Location: "Centennial East",
    ReadOnly: "True",
  },
  {
    Name: "miguel.ramirez",
    Phone: "x5557",
    EMail: "miguel.ramirez@gentex.com",
    Manager: "Kevin Miller",
    Location: "Centennial East",
    ReadOnly: "False",
  },
  {
    Name: "justin.hampton",
    Phone: "6162837562",
    EMail: "justin.hampton@gentex.com",
    Manager: "Jasen Mcmann",
    Location: "Centennial East",
    ReadOnly: "True",
  },
  {
    Name: "wesley.potter",
    Phone: "6166107828",
    EMail: "wesley.potter@gentex.com",
    Manager: "Stan Church",
    Location: "James Street",
    ReadOnly: "True",
  },
  {
    Name: "elisa.roche",
    Phone: "6169942521",
    EMail: "elisa.roche@gentex.com",
    Manager: "Jerry Parker",
    Location: "Centennial East",
    ReadOnly: "True",
  },
  {
    Name: "blake.adams",
    Phone: "6168365538",
    EMail: "blake.adams@gentex.com",
    Manager: "Ken horner",
    Location: "Centennial East",
    ReadOnly: "True",
  },
  {
    Name: "hayden.huber",
    Phone: "9895063442",
    EMail: "hayden.huber@gentex.com",
    Manager: "Andy Plantenga",
    Location: "Centennial West",
    ReadOnly: "True",
  },
  {
    Name: "daniel.jeffery",
    Phone: "6163180803",
    EMail: "daniel.jeffery@genex.com",
    Manager: "cobb",
    Location: "Centennial East",
    ReadOnly: "True",
  },
  {
    Name: "logan.estepp",
    Phone: "x6735",
    EMail: "logan.estepp@gentex.com",
    Manager: "Kent Lubbers",
    Location: "Centennial East",
    ReadOnly: "True",
  },
  {
    Name: "katee.crowder",
    Phone: "6735",
    EMail: "katee.crowder@gentex.com",
    Manager: "Ben Kloss",
    Location: "Centennial East",
    ReadOnly: "True",
  },
  {
    Name: "alex.arent",
    Phone: "5152",
    EMail: "alex.arent@gentex.com",
    Manager: "Jim Looby",
    Location: "Centennial East",
    ReadOnly: "False",
  },
  {
    Name: "david.hearn",
    Phone: "6169010335",
    EMail: "david.hearn@gentex.com",
    Manager: "Jim Looby",
    Location: "Centennial East",
    ReadOnly: "False",
  },
  {
    Name: "nicole.danz",
    Phone: "x5714",
    EMail: "nicole.danz@gentex.com",
    Manager: "Jasen McMann",
    Location: "North Riley",
    ReadOnly: "False",
  },
  {
    Name: "julian.whitters",
    Phone: "4697",
    EMail: "julian.whitters@gentex.com",
    Manager: "Looby",
    Location: "Centennial East",
    ReadOnly: "False",
  },
  {
    Name: "nicholas.routsaw",
    Phone: "6164272331",
    EMail: "nicholas.routsaw@gentex.com",
    Manager: "Stan Church",
    Location: "James Street",
    ReadOnly: "True",
  },
  {
    Name: "nathen.keasey",
    Phone: "6165021770",
    EMail: "nathen.keasey@gentex.com",
    Manager: "Scott Thompson",
    Location: "Centennial East",
    ReadOnly: "True",
  },
  {
    Name: "jeff.zomerlei",
    Phone: "5157",
    EMail: "jeff.zomerlei@gentex.com",
    Manager: "Scott Thompson",
    Location: "Centennial East",
    ReadOnly: "True",
  },
  {
    Name: "christopher.peterman",
    Phone: "(231)580-9904",
    EMail: "christopher.peterman@gentex.com",
    Manager: "Kevin Miller",
    Location: "Centennial East",
    ReadOnly: "True",
  },
  {
    Name: "adam.lee",
    Phone: "6167721590 ext5765",
    EMail: "adam.lee@gentex.com",
    Manager: "David Slater",
    Location: "Centennial East",
    ReadOnly: "True",
  },
  {
    Name: "josh.holovka",
    Phone: "516-3516",
    EMail: "holovkajosh@ymail.com",
    Manager: "Jim Lobby",
    Location: "220 Riley",
    ReadOnly: "True",
  },
  {
    Name: "Derek.Troxell",
    Phone: "4241",
    EMail: "derek.troxell@gentex.com",
    Manager: "Chris Carter",
    Location: "Centennial East",
    ReadOnly: "False",
  },
];

const run = async () => {
  if (process.env.NODE_ENV !== "test") {
    console.info("Refusing to seed outside of NODE_ENV=test");
    return;
  }

  const domain = process.env.DOMAIN;
  if (!domain || domain.length === 0) {
    throw new Error("DOMAIN not specified");
  }

  const knex = db.getConnection(domain as any);

  //   const elementTypes = Object.keys(ElementType)
  //     .filter((elementType) => !elementType.match(/^[0-9]+$/))
  //     .map((elementType) => ({
  //       Type: elementType,
  //     }));

  //   await knex("ElementTypes").insert(elementTypes);

  //   const propertyTypes = Object.keys(PropertyType)
  //     .filter((propertyType) => !propertyType.match(/^[0-9]+$/))
  //     .map((propertyType) => ({
  //       Type: propertyType,
  //     }));

  //   await knex("PropertyTypes").insert(propertyTypes);

  await knex("Users").insert(seedUsers);

  await db.destroyAllConnections();
};

void run();
